apiVersion: apps/v1
kind: Deployment
metadata:
  name: universe-datascraper-mediafiles-monitor-consumer
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - universe-datascraper-mediafiles-monitor-consumer
              topologyKey: topology.kubernetes.io/zone
