apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/universe-datascraper-monitor-producer
patchesStrategicMerge:
  - patch-affinity.yaml
patchesJson6902:
  - path: patch-replicas.yaml
    target:
      group: apps
      kind: Deployment
      name: universe-datascraper-monitor-producer
      version: v1
commonLabels:
  app: indexer
  component: universe-datascraper-monitor-producer
  environment: prod
configMapGenerator:
  - name: universe-datascraper-monitor-producer
    literals:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIARDONMETSDXC2YHRN
      - AWS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/076129510628/prod-datascraper-transfer-monitor.fifo
      - ETHEREUM_NETWORK=mainnet
      - APP_ENV=prod
      - PORT=8080
      - DEFAULT_START_BLOCK=14413456 #Latest block as of March 18, 2022 7:54pm EST
      - BLOCK_DELAY=2