apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - namespace.yaml
  - ingress-redirect-www.yaml
  - sources
  - redis
  - api
  - notifications
  - postgres-proxy
  - scrape
  - universeapp-backend
images:
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/kekbackend
    newTag: "962fe4f"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universeapp-backend
    newTag: "dev-3a513ed"
