apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - namespace.yaml
  - ingress-redirect-www.yaml
  - sources
  - redis
  - api
  - notifications
  - postgres-proxy
  - scrape
  - universeapp-backend
  - documentdb-proxy
  - marketplace-backend
  - marketplace-indexer
  - universe-watchdog
  - universe-datascraper-api
  - universe-datascraper-mediafiles-consumer
  - universe-datascraper-mediafiles-producer
  - universe-datascraper-metadata-consumer
  - universe-datascraper-metadata-producer
  - universe-datascraper-transfer-consumer
  - universe-datascraper-transfer-producer
  - universe-datascraper-block-consumer
  - universe-datascraper-block-producer
  - universe-datascraper-contract-reader
  - universe-datascraper-monitor-consumer
  - universe-datascraper-monitor-producer
  # To enable when 1155 support is enabled
  #- universe-datascraper-owners-consumer
  #- universe-datascraper-owners-producer
  
images:
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/kekbackend
    newTag: "962fe4f"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universeapp-backend
    newTag: "5c8b8c3"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/marketplace-backend
    newTag: "main-aa3ced9"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/marketplace-indexer
    newTag: "main-3223d9d"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-watchdog
    newTag: "38f8fd3"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-api
    newTag: "main-129f52c"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-mediafiles-consumer
    newTag: "main-7cc3176"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-mediafiles-producer
    newTag: "main-00122f6"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-metadata-consumer
    newTag: "main-3d3c02e"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-metadata-producer
    newTag: "main-3025947"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-transfer-consumer
    newTag: "main-d836b44"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-transfer-producer
    newTag: "main-35cf6a5"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-block-consumer
    newTag: "main-c8214a9"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-block-producer
    newTag: "main-e03ec1d"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-contract-reader
    newTag: "main-59a7936"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-owners-consumer
    newTag: "main-3cdeebe"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-owners-producer
    newTag: "main-e4125b8"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-monitor-consumer
    newTag: "main-4e77ae4"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-monitor-producer
    newTag: "main-318a8de"
