apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/documentdb-proxy
patchesStrategicMerge:
  - patch-cmd-args.yaml
  - patch-service.yaml
  - patch-ingress.yaml
commonLabels:
  app: backend
  component: documentdb-proxy
  environment: dev