apiVersion: apps/v1
kind: Deployment
metadata:
  name: universapp-backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    spec:
      initContainers:
      - name: db-migrate
        image: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universeapp-backend:dev
        command: ["npm"]
        args: ["run", "db:migration:run"]
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: universeapp-backend
          - secretRef:
              name: universeapp-backend
      containers:
      - name: main
        image: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universeapp-backend:dev
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: universeapp-backend
          - secretRef:
              name: universeapp-backend
        ports:
          - containerPort: 3000
            name: http
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
      serviceAccountName: default
