apiVersion: v1
kind: Secret
metadata:
    name: scrape
type: Opaque
stringData:
    KD_DB_PASSWORD: ENC[AES256_GCM,data:5Liuww6SKM4LfWk3O0lGrciFcliqtHqC,iv:M5Z8c0UjWBHHwaaz3LCHxDibVpvYmz4OQOUhEP6tVVc=,tag:sI6t3Rua8EOJfbPqB4ammA==,type:str]
    KD_ETH_CLIENT_HTTP: ENC[AES256_GCM,data:242wFkFd1F5CcXOh1B7g1Di7VnvKB2NI5R5nRn8HDz97bpPPfKcwCc9wT3FqZoxKNtfnBmcJ6WH12JaDoQ==,iv:JCu1lXCwaxn1yJH0wlUN+m21XBDOuY0lADxn4wo0oYo=,tag:gWjYskV3TzrTo9zqK85BFQ==,type:str]
    KD_ETH_CLIENT_WS: ENC[AES256_GCM,data:01VG8cy81qLYmRlGbZy/SZFDm10pnORZ8XVvb1mAg7dw81xKZOVHL5zTjlT4wHS5/K7NQB4wGYJSm/CqUYc=,iv:vg7M4WGTp4qWL6iEOZb3U1mbDux6PukuB/sXdEsML2A=,tag:rL1x0XIG5LVIgeGtxOqFFw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:076129510628:key/eab03aa9-c5da-4c1b-807b-686aed83fb2c
          created_at: "2021-05-25T13:49:02Z"
          enc: AQICAHj0qDpfgO9wb8Ne63a0VPqmK07P9Pqm4dt4axNmrKd7LAHHe17ds9KWGYQxriR3YRzjAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMeCpR1JGcBNPpwl9kAgEQgDtcq6Myd7tG0MfOQHn11ZHgi0MP038LONmpK8Ukpy9+Fmx7WPa5fFXITb3IJ1qh0UObzclPisH2FVkgSg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-25T13:49:03Z"
    mac: ENC[AES256_GCM,data:0m1tnsvy/QdojDQC/dl0XNzErMUgcRMVdTgeOpzGOOoE2KqSLUr5j29iLXPr1LYDCFZeIl1jTWnjXIBWgejMdjvwZvf50Wh+vjevfTYNwI6oINcChNZwIuXG4PQ5sj8dB/ZYMHMszE7xrOECptzvbLr47sU8j8+truSh43ZHgto=,iv:Wt2zTIJ1ePaeORyLpv70WGCmUDGiJjnDibi08vTZRYw=,tag:2hiKBNDf34WX+nOhps2w5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
