apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/universe-datascraper-mediafiles-consumer
  - secret.yaml
patchesStrategicMerge:
  - patch-affinity.yaml
patchesJson6902:
  - path: patch-replicas.yaml
    target:
      group: apps
      kind: Deployment
      name: universe-datascraper-mediafiles-consumer
      version: v1
commonLabels:
  app: indexer
  component: universe-datascraper-mediafiles-consumer
  environment: dev
configMapGenerator:
  - name: universe-datascraper-mediafiles-consumer
    literals:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIARDONMETSJIL57BAC
      - AWS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/076129510628/rinkeby-datascraper-media.fifo
      - VIDEO_BUCKET=universe-rinkeby-datascraper-video
      - IMAGE_BUCKET=universe-rinkeby-datascraper-images
      - AUDIO_BUCKET=universe-rinkeby-datascraper-audio
      - MODEL_BUCKET=universe-rinkeby-datascraper-models
      - MISC_BUCKET=universe-rinkeby-datascraper-misc
      - ETHEREUM_NETWORK=rinkeby
      - INFURA_PROJECT_ID=24dfd27eacf24481819d98036173cfaa
      - INFURA_IPFS_PROJECT_ID=25vSfS4V1v4iI3pweR494fC2yJ4
      - SESSION_SECRET=XYZDAO
      - IPFS_GATEWAY=https://ipfs.infura.io
      - APP_ENV=dev