apiVersion: v1
data:
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:G5uhHVSws4wplb4Ln5ySkMJsixdTAeMhC5qlmApqTpGeOXCEGE/VzpVY0hjS/4nIJXPhshkelfc=,iv:PMYgv8SqtX63Qml0LzMi6MxiSS7WVOSJwVE62or94sY=,tag:i2QoDjR78KeP8G37JpsWqA==,type:str]
    INFURA_IPFS_PROJECT_SECRET: ENC[AES256_GCM,data:arhZKr6zcxGVGWXJBg6272d0TawByYH8XNIQhu4dsn1oVDaSlOl1W0UbVo0=,iv:AUGry7oniuEwnsR7SfifCE05xY+jR2n1GI11KdovqY8=,tag:3hnvpV+rxEntw42Uaq9XcQ==,type:str]
    MONGODB_URI: ENC[AES256_GCM,data:FgguI1OCGBwXDo51NusjfYh+Ei23qR6L0INqf51sttuBEjanzDAC3YvnVY00fF8c7Waan5xN+gIp5b1Ts8HeCrc72luI/LSqKfepJRjhb1FrTtEASPFVsAmAB8evk+HbefpERqtgv9maTITGz/fuHdegSU8HNLOiWk0gCbY9vqH1tdjpfC4RYoxx6tsmkGyeXXn6RP5TR5SqSuyjC/6Y40sMJ3YEJ+dvEX3BfNMGCNuNxAtPZYGP3Ouj0dm3RzP85WcfMn/rtLc3m+8zRQDtY7MhSsyNlAIAWrsyujSEIcyL6Mh5+/v5T4T8cChMOvfQEjxpH5JNa/AOPCdJM52puCWnyR+TE/fKsRsCqDK4FmJyHmvfz1T3INuAuUyXwMhIurZps/JgK0gZ5buJGgFVVJn5ZV0zTntBYeXNLb7nzirg3H8qPEJiuvRkJSZmyxTbKy6BP7/Nr60=,iv:Jf/2mfMldmWywtiXjSwIxR47U+7QTCRZQ/MML8jtc3I=,tag:Q4ku3IzGAdKw/cQaSDcDVQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: universe-datascraper-mediafile-consumer
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:076129510628:key/f019707e-98d5-454b-adcd-a4b8ccc35f44
          created_at: "2022-03-04T15:11:56Z"
          enc: AQICAHicCjtoxmBmz2MO3QTlS3370ieytvfowEbSDe18IeRxZAHt436c+BpcLf8YXLnUJA4JAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMofBY/Wg6gbEoX4JHAgEQgDu6ICCG1tYerwF8x9w8rF4/H2V7zTvha5Q1B4UnpvHXfxqfixUZKlPsUdOT10La7OMvUEMnO8ZIHhvVqg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-04T15:11:57Z"
    mac: ENC[AES256_GCM,data:+4N2IV3DawfZkhBV9rhwmkuzZu5hrvArpQ0ZI8OMnCIkcN2YTeaWRdK+WKlxwO2GrGYF7e7sRJ/pfwIGxSA1pCzNaaec+iwXa7aGQ/bGYW9iyYV96AlI/TJNOw0jC+hByMbY/ye1xrq7Cz0qjCX/2CyudVrVcGD2SubsHU3Tpk8=,iv:k762gUCfSOKVXIBf1TaTOUbfM5nApZfZuBNNXtu2vuk=,tag:gdGJHUcJh6wqz923oUiwoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
