apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/universe-datascraper-mediafiles-producer-backwards
patchesStrategicMerge:
  - patch-affinity.yaml
patchesJson6902:
  - path: patch-replicas.yaml
    target:
      group: apps
      kind: Deployment
      name: universe-datascraper-mediafiles-producer-backwards
      version: v1
commonLabels:
  app: indexer
  component: universe-datascraper-mediafiles-producer-backwards
  environment: dev
configMapGenerator:
  - name: universe-datascraper-mediafiles-producer-backwards
    literals:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIARDONMETSJIL57BAC
      - AWS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/076129510628/rinkeby-datascraper-media-backwards.fifo
      - ETHEREUM_NETWORK=rinkeby
      - APP_ENV=dev
      - ETHEREUM_QUORUM=2
      - SOURCE=ARCHIVE
      - MONGODB_URI=mongodb+srv://universe-db-account:y7rYKn6Bw41PbB3E@universe-dev-cluster-at.lrbek.mongodb.net/dev-universe-datascraper?retryWrites=true&w=majority&ssl=true
      - SKIPPING_COUNTER_LIMIT=180
      - QUERY_LIMIT=1000