apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/scrape
  - secret.yaml
patchesStrategicMerge:
  - patch-affinity.yaml
  - patch-env.yaml
patchesJson6902:
  - path: patch-replicas.yaml
    target:
      group: apps
      kind: Deployment
      name: scrape
      version: v1
commonLabels:
  app: backend
  component: scrape
  environment: dev
configMapGenerator:
  - name: scrape
    literals:
      - KD_API_PORT=3001
      - KD_API_DEV_CORS=true
      - KD_API_DEV_CORS_HOST="*"
      - KD_DASHBOARD_PORT=3000
      - KD_DASHBOARD_CONFIG_MANAGEMENT_ENABLED=true
      - KD_DB_HOST=dev-universe.cotqfbtbif7j.us-east-1.rds.amazonaws.com
      - KD_DB_PORT=5432
      - KD_DB_SSLMODE=disable
      - KD_DB_DBNAME=kekdao
      - KD_DB_USER=kekdao
      - KD_ETH_CLIENT_POLL_INTERVAL=15s
      - KD_FEATURE_BACKFILL_ENABLED=false
      - KD_FEATURE_LAG_ENABLED=false
      - KD_FEATURE_LAG_VALUE=10
      - KD_FEATURE_AUTOMIGRATE_ENABLED=true
      - KD_LOGGING="*=info"
      - KD_REDIS_SERVER=redis-master:6379
      - KD_REDIS_LIST=kekdao
      - KD_ABI_PATH=./abis
      - KD_STORABLE_KEK_ADDRESS=0x86dEddCFc3a7DBeE68cDADA65Eed3D3b70F4fe24
      - KD_STORABLE_SUPERNOVA_ADDRESS=0x8Fd650aC7522DA8815BC27ab8a8174f3C9ca355A
      - KD_STORABLE_GOVERNANCE_ADDRESS=0x5131D4f8B1D5Fa3f50E139eE3E545d5e8C2Bf731
      - KD_STORABLE_YIELDFARMING_ADDRESS=0x831B60137F2f9F37846BEB61C8E0913eb4BeC41b
