apiVersion: v1
data:
    MONGODB_URI: ENC[AES256_GCM,data:V1AqfVdqOe4U3/7XpwgvRpxikjhjwnr+7n0M2slomawQ5D4SkDHqhqZh+D7jVeX3Wz7lCyrnEICJgSQjkLpWnOg2inNG2r0G0BKikBrcohb8RkhEdsCjII9yxNm85JPh5SuPeCz6ZpdYQDldV/Ssslr+tJCKCQ3Cth9QZgSUn5+VqmIyUi1ghAjnouYeZAIiZyOCORkMQw+hUZUQinkZYcsNJte/ipAWy/JwQDfRYhaWQTnrXVNqYt4hmSVwqSS7luwDAzifFSkw9W+P+iLqd7uG8xwveDfmd0Int+RVAQ7zfAB+ZBabTHgSgfqXR3Ak,iv:XfhRWtRNAwZRsn1UuWwT9fYA0NvbVcvf+ARLmmMUR40=,tag:zqJe4+RNJ7HcFuymmd77jg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: universe-datascraper-api
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:076129510628:key/f019707e-98d5-454b-adcd-a4b8ccc35f44
          created_at: "2022-02-15T15:35:59Z"
          enc: AQICAHicCjtoxmBmz2MO3QTlS3370ieytvfowEbSDe18IeRxZAF9PucbTkaqWx44mw2LRRFiAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMcnXtVbxa0ddPFxmGAgEQgDvKrjAOl4E/mXGTyM8hTZLtC33HQKtF9MtYSyIT2uubPRrSQ+Pl8OM4ZgScwuPVX5pcDE8rX1uRtsJIIA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-15T15:35:59Z"
    mac: ENC[AES256_GCM,data:GZstc3JRU6CtURBvul2FnyqE3VcjFodwVyYE8iMuE51fL8CypOIxd1dvRixNRFa2LXTYnTPXOOLVz5Me1T/kfEZJCiIK+iqnIVw9zmvYWeZbaFr8jekD0V5pKVVoai6qOWrRdT5GzzqY6G6kFwPCytJ3/6WOBPGfXJyeAmNSHmA=,iv:7BTAePJq8IhanHtmRuDvg2CXCN8SZMsCFp8upDmtNHo=,tag:jk6RV2xLu27iQPN08Wo1qA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
