apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/universe-datascraper-metadata-consumer
patchesStrategicMerge:
  - patch-affinity.yaml
patchesJson6902:
  - path: patch-replicas.yaml
    target:
      group: apps
      kind: Deployment
      name: universe-datascraper-metadata-consumer
      version: v1
commonLabels:
  app: indexer
  component: universe-datascraper-metadata-consumer
  environment: prod
configMapGenerator:
  - name: universe-datascraper-metadata-consumer
    literals:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIARDONMETSDXC2YHRN
      - AWS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/076129510628/prod-datascraper-token.fifo
      - ETHEREUM_NETWORK=mainnet
      - SPECIAL_CASES_OPEN_SEA_1155_URI=https://api.opensea.io/api/v1/metadata
      - APP_ENV=prod
      - PORT=8080
      - ETHEREUM_QUORUM=2