apiVersion: v1
kind: Service
metadata:
  name: universe-datascraper-transfer-consumer-backwards
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
