apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logstash
spec:
  releaseName: logstash
  targetNamespace: dev
  interval: 5m
  chart:
    spec:
      chart: logstash
      version: 3.6.20
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: dev
  values:
    existingConfiguration: logstash
    extraEnvVarsSecret: logstash
    persistence:
      enabled: true
      storageClass: ebs-sc
      size: 8Gi