apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logstash
spec:
  releaseName: logstash
  targetNamespace: dev
  interval: 5m
  chart:
    spec:
      chart: logstash
      version: 3.6.20
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: dev
  values:
    image:
      repository: opensearchproject/logstash-oss-with-opensearch-output-plugin
      tag: 7.16.1
      debug: true
    extraEnvVars: []
    persistence:
      enabled: true
      storageClass: ebs-sc
      size: 8Gi
    input: ""
    filter: ""
    output: |-
      opensearch {
        hosts => ["https://vpc-universe-dev-rctynsnc4sybvk4uxetqyhwk3a.us-east-1.es.amazonaws.com:443"]
        index => "postgres-%{+YYYY.MM.dd}"
        user => "kekdao"
        password => "Universe!!!420"
      }
