apiVersion: v1
data:
    LOGSTASH_PASSWORD: ENC[AES256_GCM,data:Dx3NlsoPnp9zJtJSrNc8klak6jrl5rC/ZwnNCw==,iv:b0FqQUyadDlFNeXbwRICn1HEh7UeTLnIKcum/MH7JKY=,tag:XYP4n69MkbkoH2zfpcF9pQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: logstash
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:076129510628:key/f019707e-98d5-454b-adcd-a4b8ccc35f44
          created_at: "2021-12-16T16:24:57Z"
          enc: AQICAHicCjtoxmBmz2MO3QTlS3370ieytvfowEbSDe18IeRxZAFouGti7pScH7v+dCkvKQS6AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMLPDwVmfZtUhXRspzAgEQgDsE8Ygbr6uJC+4iBrjsHkMc340qhzark9AmafR2/hSStmV3EhBGDo47Hw0nHu/nU4Gn5hPi6SbQFY+Y/g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-16T16:24:57Z"
    mac: ENC[AES256_GCM,data:EBm1uzBTND9uMzkKmJqC2dhxGuZeMOhu01eSuCxpa8g561RFuWR1M+fVUqR6Nl8NVRzmmB4932nLeZJZPlVOvLIE5l4PsCM/eVJOBaPzCgDFNyVnABS9ToUkVn+mZHLgDgAjF5I8arE7o5P+jDU44L9ncv1qk9BwsbO08BV3vGU=,iv:oOTsuZUUoJ1FeGdBbydq/1qXFgySNDlC8V9tdwS9KsQ=,tag:5TvIMvgBBXD4tyB+dV1hvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
