apiVersion: v1
data:
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:L0nGSk89GwkO9dUFwHsVmT5HtLw2ZnFG/SWrsBfQAJCQ+zgfncRIQKhNk53jzPuidDt8D2I7kjE=,iv:NLAiamwpyeSjgxUU7X3TieFDlii/PG9YmXupQCaWxSc=,tag:LOIzBstryByvSVodfoY8NQ==,type:str]
    MONGODB_URI: ENC[AES256_GCM,data:g417x4yW284EWZ2ACKBAjIA06+GXqPTCYsC/jbviKyJKYWw0uKDeBYONjWqxnpN1DwrSXCyiuC7+vSdn3eQta4fpD5+OcdysNZCzx6+Nkt1zyWeBEfr0HkfzojwZgRdBc3Ame97hpvRBVbk11lSsFrkMeA4pxb6dhx1kklknPM1dQMGQDsEOe/a8qu8Eg5XUnDXE1BO2nDVVDdA/CGlloUylNEyEJxm53ubkmO4UFUN8Dcq7s4JkxMZGztA9EKgqcUc3qjCvLndJL3ldtLmukfUL+KLlh+pa+pmN37aePIR/ZsLJ2xys9Kr61fUiMrcuy45Qg6AhsrQlSn46YxRRtAY9vW3uhb6jyeU14lr0+7vBTGOxqXE2nHEtgDdRkT49lNB6N7cY/3+rUKP3fPYfZtxsgSiYI4G9VDMIqK2cHOqTLtIV17UiKNhfkh1zPbOV/2N/ng==,iv:jEa+NCgbI+yB8qsxjBLKcucQSx8KnoZFjapEosxNJlc=,tag:HeHxrY90kYNCAexDnvBo8A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: universe-datascraper-block-producer
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:076129510628:key/f019707e-98d5-454b-adcd-a4b8ccc35f44
          created_at: "2022-02-16T00:11:36Z"
          enc: AQICAHicCjtoxmBmz2MO3QTlS3370ieytvfowEbSDe18IeRxZAFcENaK6SefTzUzDcLvqUgCAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMP+AKF704EROdpK0HAgEQgDtMxODLHxzblhuzjZR/bvLjhD9BR4pcB1oTz9vKJOE8RBYU2Fxf3hvE7f4xCHzmDNaBEbqUHPjaPPX6KQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-16T00:11:36Z"
    mac: ENC[AES256_GCM,data:dnCG4RsMlpRBMaUy2Hfd1tsREV0I4h4wvvIp05tibmPLrlgqYMSmmyPKW3on4eUQAN5Ndi04o31CwQqoPtnVbGCEzLNTb4zg3ixikDrvxRfWfnmfxaWxCVBwqPZG246TuM9UDailYcjNIFV4XBHYgQFz7ZBw34OMLGD7W7g6RCw=,iv:My6o3SmvnAU0bsEXM5f/PV9fZFfOg8UC5S3QFkhzEe0=,tag:0O+y2sosXHZl0CwGVZXo6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
