apiVersion: v1
data:
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:d/CpClsGt8b3HaVssSHXzgfj+jZO9AFfNwg/9iWyQjBgu1tHgpzteGHHofae9gOvfesgILUYeo0=,iv:aK08AP8QUcJee7DYnxwP6XgvM9JgRRygMMAS0Qm3Rpg=,tag:APZqeiixJjRvpojTX9NPCg==,type:str]
    MONGODB_URI: ENC[AES256_GCM,data:cw0p5+S2y8K8jLcqmru4Y/baDsHyAMcirdjeiw9wvMHB19uQcD9xcFdWZCFywy9AH7o/mX0YbCeuIshTTJTvi8o+6hWg0CGw/7AhjwBZBjqEu1nK5n7LXqDNBOW04CWrLNJqzQ7A/DmwnHaWJ/wE6bx1auWonYEyNm6roQAKNZ4dawaevmACrcRsI34ansxo8yLxLdp49W6mvtm3j3ZBzPXbuifceoRuaNqXfmal70jKwvmA2+9yjC/IfZyTevbJzOSzXzse2aC8Ygdw1bZtWhNDPQYdf27kTePTM4dsz6TLvBeyDHloJmzvNkpt9YvJrDwgDHFiGL52uuoEyc2zgxiXpaLSlPhMNa58UW7mdrVMzVbxXx7GhqDMHDTKQsLx0cDutlA9y6nP+XlmxZ4egxbSmgeUMxLzCuAua+kX+R1HXN9FM9DlbepVJL1KiDtNdQ/GptoPfC0=,iv:hMRYPEHQ386h4XcyaqGdJTSvcCirYeBNqtopTMKlyLo=,tag:/3YmfnbvJRqbN/hPFh4KGg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: universe-datascraper-metadata-producer
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:076129510628:key/f019707e-98d5-454b-adcd-a4b8ccc35f44
          created_at: "2022-02-17T18:49:00Z"
          enc: AQICAHicCjtoxmBmz2MO3QTlS3370ieytvfowEbSDe18IeRxZAFUe0IxDet+9BSJ5NpZrfDDAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMKzLf/xL5lzF+0XvpAgEQgDsl/O/LPnDEIvgkm5sZE7ILHHamFtIStcmoXSSW9XzcczzpVXeaOMSWFRCGQ0R4AOLjIYHW/vdWVy1iyA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-17T18:49:01Z"
    mac: ENC[AES256_GCM,data:QI7FttV9o319r7Lv44Uyu20hK60L9tdFBwjXt96VVebDFynjJ34ktjPrBNIDHqtVe49rWgjQLc3H9Q/uCpo7SHoIDgEPyuGPUqt+vDi+0UvZrLfyiUbCoEbbr91qRiVM4I8Q0jatWZhIIAKNCvV4+5OE+drqbIdSEaBox7bCZWg=,iv:fYzPAWhMc8w4+boqVU2OZNPPRxqGeYM2KoUzLcXgvKM=,tag:RTwLEz8x/SAoK7aaZpk2bg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
