apiVersion: v1
data:
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:cKZptBoo7Nja4NYY4XXDTpkhwanukUOd5WsTPrpOa8LipD1AU6MtjHXdKCNIF6L0KTIrxmDDA8E=,iv:DP+PCfYejVDfQH5qCByeo+GC7IcAInZKOlxXg68pWwI=,tag:jmVzJHp48kVMyupk6zXReg==,type:str]
    MONGODB_URI: ENC[AES256_GCM,data:aHWbWM2bJNWPpgDHyDdZt4KyPFS3q+75NM9zFDYtSLJDZs1ZoOXo/QXfLiAT+AaxNSmvr5/jMiGjk29YZoXum3nMYOYQRvy3DARUVR7b7TfaEO1aDNFxxVQ8I8Fp4qmIeHFS3TXnLsTzHAEZVbN2QO28XF4FYkHvvqHRGR1b1pThBangG9EAE9mNLh0wEObbdPR63AR7XpgMobr9Jwz8BBr/Q9gdFb3tn4BnIeXTJwtFsNnvBAWpxVTi1nobjucN0BjSYztOhlNth/KvDSuI/lwyP0hJYbWXaVvmOncJO5GN+3DBxehHkPq0OORNnW5D,iv:DOEBcajdTNkDKORxrkk3rWHc6knlhmVQj2BEtLPz7z4=,tag:iTWe7zpF64SK7ulaXnwYtg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: universe-datascraper-metadata-producer
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:076129510628:key/f019707e-98d5-454b-adcd-a4b8ccc35f44
          created_at: "2022-02-15T19:54:23Z"
          enc: AQICAHicCjtoxmBmz2MO3QTlS3370ieytvfowEbSDe18IeRxZAHBYm9/c2FqJroRVFaBhqLaAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM9zCw2yFt8SIqxhRmAgEQgDthAa9q8RZsJB/v+ghRfSi8S2kOM/itGKfpLPhiXx1AtvAP8dQvAKjpxEFBjVBBWZUKH7SU32YoMkpdhw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-15T19:54:23Z"
    mac: ENC[AES256_GCM,data:bLHcfR2z9ocjmuyCzUzL75Z+FrjXQ01kG0dM3V5k+vTfhf02pf/sJox6Z59pdI5+x6GWiR0zAd+gOPYMIyhyJnoxcPyaY0JBUWjk8fz2qnfVQhjsST9tiOxytW3y5XwkmwRZs6+vUG7EG0eglRxGBkPXUf5jO/XZb6YOrcGln8E=,iv:wcbAbWTzwBWuf3mavBgigehRggv6MJ4WWtMgHm6tGvg=,tag:yaoGKS4MhgEnW1IoUSkr8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
