apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/universe-datascraper-transfer-producer
patchesStrategicMerge:
  - patch-affinity.yaml
patchesJson6902:
  - path: patch-replicas.yaml
    target:
      group: apps
      kind: Deployment
      name: universe-datascraper-transfer-producer
      version: v1
commonLabels:
  app: indexer
  component: universe-datascraper-transfer-producer
  environment: dev
configMapGenerator:
  - name: universe-datascraper-transfer-producer
    literals:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIARDONMETSJIL57BAC
      - AWS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/076129510628/rinkeby-datascraper-transfer.fifo
      - ETHEREUM_NETWORK=rinkeby
      - INFURA_PROJECT_ID=24dfd27eacf24481819d98036173cfaa
      - IPFS_GATEWAY=https://graviton.mypinata.cloud/ipfs/
      - APP_ENV=dev
      - PORT=8080
      - BLOCKS_INTERVAL=2000
      - MESSAGES_PER_PROCESS=100
      - ETHEREUM_QUORUM=2