apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
spec:
  releaseName: redis
  targetNamespace: auctions
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 14.1.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: auctions
  values:
    architecture: standalone
    master:
      persistence:
        enabled: true
        storageClass: ebs-sc
        size: 8Gi
