apiVersion: v1
kind: Secret
metadata:
    name: scrape
type: Opaque
stringData:
    KD_DB_PASSWORD: ENC[AES256_GCM,data:7eBrZ//qBacRQb77Qqyaw9Vr2EiJIABl,iv:s152/+0iy/zhwq4H1NK8Q+JRFzcj2U2yJEebj4Ct+DM=,tag:T9F4EceFLMe4c4MvRawnpA==,type:str]
    KD_ETH_CLIENT_HTTP: ENC[AES256_GCM,data:bSTaYJbBgd7HEYbcHYb9kWkxuGVtZS9twepl0qtTxDz9BBfPyH3yW4O0rgNrlNOVn70KkxVA6n3BInsDYA==,iv:hHHnQ9H/F2hfVsYG0iEubHxLt2KedA14G2PgIOQqWbU=,tag:xwVx+Y4nZikd1kvvQQHtEA==,type:str]
    KD_ETH_CLIENT_WS: ENC[AES256_GCM,data:uo9S++49jwF3m0KOnOMNSyoWLA59qgeVh49qOuy/d50x15hHNdxWuhASZrVGV/Q+wMVS3AszFm8IwjTvdPQ=,iv:ZCGYOqwFgPK6q3JswaQm0XLv118pJ51DKymAZwLmFk8=,tag:pn00hx9S2rrukbdTq/uEUQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:076129510628:key/f019707e-98d5-454b-adcd-a4b8ccc35f44
          created_at: "2021-08-25T10:34:39Z"
          enc: AQICAHicCjtoxmBmz2MO3QTlS3370ieytvfowEbSDe18IeRxZAGITmPz9sm3ERmRoMAvSJ3rAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMK+3/BR82ZC5cH4aaAgEQgDsMapuCrXfwGzpedgM7BKX1mdUTDMSy2SZ9yYQRmb4NRl+XjRx7CQQ1B/O3ksmSgm/dHs87Nk4d5JL6xw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-25T10:34:40Z"
    mac: ENC[AES256_GCM,data:GJx1splOoZNFCVg/WcSdTAYTmi0ScSynUJPpqLTg81607ccwBuIdsLbto64l6shoMn4a+1MzkrUpHAtdBXaRKXSdETqIp021see1tCx0qBlcXWODxTdYMqUjNs2Li+ar+36wLp901jQBwWKllMRX39/R8gSm8rfxaNUrLq8/ZOo=,iv:yBsTqv+kj/OTq+hNFnsZ3JYCSdzoTudkl1Dnv4fpSFY=,tag:Au+SxMIwDC79c7SZTbQ6yg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
