apiVersion: v1
kind: Secret
metadata:
    name: scrape
type: Opaque
stringData:
    KD_DB_PASSWORD: ENC[AES256_GCM,data:n/oDWHH92Bg1qnlosBgqRak2MkZVMU22,iv:Nk7MVWeoL/5Ebm8UvpLHLdyGnrAfTUl908lM2Pkz/+U=,tag:eHPfm7oEColR0dYths4+mQ==,type:str]
    KD_ETH_CLIENT_HTTP: ENC[AES256_GCM,data:UvSAifkKzsqHdFG5u3MDLZvsMgjwZhCpa9XDTJYzqHmZsI5vF/TVFpdkYLWsk59E0F3/RF9RzdfYBJ/IGw==,iv:e2H4WzV4pCLJxuMjVPPUliLneElhVScQ+V0GFUAk2n0=,tag:InxLlNp7s6pKjsF5ptDYVg==,type:str]
    KD_ETH_CLIENT_WS: ENC[AES256_GCM,data:/e2YE35IrE3/Ri6cNEzf3KbNiy+NgkwxeSFVARQbD/rI38GPXTY3K+ZXpx32x0O8m0rtpIGASGRpcLMzut8=,iv:+gjJLeCThleI7aXyibxhPr9yw64FPIEy9iTCECbRZBA=,tag:HhNs4zC2JTjgjVMQTEuECQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:076129510628:key/f019707e-98d5-454b-adcd-a4b8ccc35f44
          created_at: "2021-08-09T09:22:11Z"
          enc: AQICAHicCjtoxmBmz2MO3QTlS3370ieytvfowEbSDe18IeRxZAGwu2QQ3UzEPIqtXjtaqspwAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMSCK3N+8fLHHVL1btAgEQgDt/TUoWOXwpo+WOK81IzkVm1rXLON8PBXsfAan4r+NQ8Vjaejf1Dvp1nXL8ajW3WgjWbyqXoexMFwXkLQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-09T09:22:12Z"
    mac: ENC[AES256_GCM,data:KJapNXdvfUbGq1KDFEJk8jncjHipMTogmajWDHZeYIyNwAjlkzGgxSuc8nWDPxt2xKTRF8jtu2Cc8BYtpN3TOETQcfCj/PLh4YFousmz1GS/QqOWsMH8ODY7Y8xJ5+bspXBewYuSmSKAJuR3G+phd7xcQiA2+eDo0UFNT3oKyVQ=,iv:gkRuzEIWLHfiJqPhvytmgUbiRu+I5VFJDj1ClmVvjBk=,tag:7eC7ns+GDbUKYCwzI4krNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
