apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/universe-datascraper-contract-reader
  - secret.yaml
patchesStrategicMerge:
  - patch-affinity.yaml
patchesJson6902:
  - path: patch-replicas.yaml
    target:
      group: apps
      kind: Deployment
      name: universe-datascraper-contract-reader
      version: v1
commonLabels:
  app: indexer
  component: universe-datascraper-contract-reader
  environment: alpha
configMapGenerator:
  - name: universe-datascraper-contract-reader
    literals:
      - ETHEREUM_NETWORK=mainnet
      - INFURA_PROJECT_ID=978f8f87fbdd4ea0b94fe0ab245b06db
      - SESSION_SECRET=XYZDAO
      - APP_ENV=alpha
      - PORT=8080