apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/universe-datascraper-contract-reader
patchesStrategicMerge:
  - patch-affinity.yaml
patchesJson6902:
  - path: patch-replicas.yaml
    target:
      group: apps
      kind: Deployment
      name: universe-datascraper-contract-reader
      version: v1
commonLabels:
  app: indexer
  component: universe-datascraper-contract-reader
  environment: alpha
configMapGenerator:
  - name: universe-datascraper-contract-reader
    literals:
      - ETHEREUM_NETWORK=mainnet
      - APP_ENV=alpha
      - PORT=8080
      - ETHERSCAN_API_KEY=85SC3SXZZA8PPRNA7NY51ZVSWSVEMPT3NK
      - RECENT_BLOCK_GAP=100000000
      - ETHEREUM_QUORUM=2
      - MONGODB_URI=mongodb+srv://alpha-db-account:KXy1IPx5N2wKLJSU@universe-alpha-cluster.jnoczua.mongodb.net/alpha-universe-datascraper?retryWrites=true&w=majority&ssl=true
