apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/universe-datascraper-mediafiles-consumer
patchesStrategicMerge:
  - patch-affinity.yaml
patchesJson6902:
  - path: patch-replicas.yaml
    target:
      group: apps
      kind: Deployment
      name: universe-datascraper-mediafiles-consumer
      version: v1
commonLabels:
  app: indexer
  component: universe-datascraper-mediafiles-consumer
  environment: prod
configMapGenerator:
  - name: universe-datascraper-mediafiles-consumer
    literals:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIARDONMETSDXC2YHRN
      - AWS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/076129510628/prod-datascraper-media.fifo
      - VIDEO_BUCKET=universe-prod-datascraper-video
      - IMAGE_BUCKET=universe-prod-datascraper-images
      - AUDIO_BUCKET=universe-prod-datascraper-audio
      - MODEL_BUCKET=universe-prod-datascraper-models
      - MISC_BUCKET=universe-prod-datascraper-misc
      - SQS_BUCKET=universe-prod-datascraper-sqs
      - ETHEREUM_NETWORK=mainnet
      - APP_ENV=prod
      - ETHEREUM_QUORUM=2