apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/universeapp-backend
  - secret.yaml
patchesStrategicMerge:
  - patch-ingress.yaml
  - patch-affinity.yaml
patchesJson6902:
  - path: patch-hostname.yaml
    target:
      group: networking.k8s.io
      kind: Ingress
      name: universeapp-backend
      version: v1beta1
  - path: patch-replicas.yaml
    target:
      group: apps
      kind: Deployment
      name: universeapp-backend
      version: v1
commonLabels:
  app: backend
  component: universeapp-backend
  environment: alpha
configMapGenerator:
  - name: universeapp-backend
    literals:
      - APP_PORT=3000
      - AWS_BUCKET_NAME=universeapp-assets-alpha
      - AWS_ACCESS_KEY_ID=AKIARDONMETSJMK5I5W2
      - AWS_S3_BASE_URL=https://universeapp-assets-alpha.s3.amazonaws.com
      - DB_DATABASE_NAME=kekdao
      - DB_HOST=alpha-universe.cotqfbtbif7j.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DB_USERNAME=kekdao
      - ETHEREUM_NETWORK=mainnet
      - MORALIS_APPLICATION_ID=IDUfhgcQFACblDaJDbcWmFtrwRjelXXqokkFnSgH
      - MORALIS_SERVER_URL=https://geeepbacb8mi.usemoralis.com:2053/server
      - REDIS_HOST=redis-master
      - REDIS_PORT=6379
      - COLLECTION_EDIT_ADDRESS=0x5473580406D12E1cBD4c00B77e158FfF0CE9424e
      - AIRWEAVE_WALLET={"kty":"RSA","n":"vZg2tFeeUUEIump3hMtiA1YxauATatlqVJOJFq0KOiQRzeXsfk7_wDgr6QCAByqwtY7suxicvZEUQUls5n-sUh0Ld1OcitRvVUDLulJ1qODtZdKf2ReIAv6DqUvjW32izTVClQiVZZDr4iJPO5AJRpy22qkfkdXFqZoQY_2TiN66WGmcFC6DAJKKyLPo8ERZfPh5Oc49CCtCb7C4NvsEFhrzq_jjpwbI2QuD3T3XdKBebC0m7bVPxgzaH063jm4utSz4KVHP5rrThkEEfwIPrZJBrDPrb1EkxCQvUjgVhUWOjbbgdukdU8Os0o2sZP2fMjsrwHkJ2nufkwjEuHRC-W9z_sIkgIY39W-4h85yarOwYzZkFcXavpq95bBiKhBNo0SOF6IqswY77QlwmR51wL-WNIPDNb9Q48YdA2llyWEKTTMJpem-C34Ywbo_FjoVJcKAXpgmqstywP4o75aKLridaLr6KcUlHwD1MWTnTjZK6kAt721KxUUjsQZA_yaDApZ15E9uIG9madX2aFJdjqCwxz9UGjGBG_GiaQMh_qn1VW73kCzCzbdWEf5JtXZ7qhuDhJL0EMlSnPSyCn1BsWgG-d-Zmrx9_VSicf7SVF23QdDbDlYbrWoHF_DtsI9lk8G5Jcd896dVMTm22wSqdjmHbYt6DqrbAf04FgYR9ms","e":"AQAB","d":"YGs1fteEUwxA1RTp_WW1Tb8a2KBmH5O8CJETSa3soo7PYyfH8qBYXjfy1McFVR-3yE2MRMYKiDls1Jrzv_E0AHp251NlLBFHIVMXiIUBA0aIVJ0d37ig2ez3pjRKxq-JCNVKLCK2X3WpEFKkesUQgpGWSHNz86WEpXENXtyJmDS1Ddt_nZ_dzX-5BsK_9ti7rdtrQyOIVEwzuDtmI8faVyeTvmSP2dSQdhjuEaiulsgr3NXFk2P-0ticYQmWPd_47viUp-bMVSm0AvWzxKeWs43KyjmJRQ4-JWXFjwmooCM0kQts8ewxlvTPQjD8eEunF1OSN4sWoL738z2lVa0ClZeVDgjfS73LoIZSnQ_FxB4P-KdtewBca5HvRXPkEllgh9YlPrAulnceCB3ybNNqw46QIr0Rt25MQMCSGKalB_is6Bd1ZKRyeA27qVVdLjqBVCmA5Z7xOfOWNTWHUR24nFfm9KCOE8r4COe_akxoxX-tdBystevD6Tr1m1F2-VHlUwlJLJgvow_uHJGuyXFWsprkymgCzd90cdQyJh30qiTXZS3yjnvh93r2Tnu-eI0m9nNo8qWSbSJb7ZcVbRN6_bgX6HQkij5nQQDVTwlVVA5SOo4bw-plliMtqTT9P40FiSblzYMDUSbYovqTzEfgU9U17Sbws-TyvA95mE7u2WE","p":"_IyOSDPv8vkPO0mo4MhC6-UCPGcg1AMvXWPa6BdumQWhsLGgHHp0HasOUYuJdifJloQFJ1U3N9U0781s_E4F3umKIOQ155amwNUdI10ixGxNbnGIh-VDc1wzYdcqAkjP55SlQDSWs51b4duwS-CcktHYcMWhYjHsOElz5NhaHkgCvW8bJBlVJujZXg77CpX2By5ey2yqd2CfPos41sGAn2jIHIdnsAPspp3Dl286HBIMaDkkq2__ZoNsMOo9GpKJmP2bwq7Rc8VIftxhJT25QY6U9WzCbAYcOZ7-F75pYYetqbfjxKw3vu4cVMNuZ7jNleJ15jDVBQdzUztw7hO8mw","q":"wC9vsYRRxFb9-F_SHwYquzRhV5Z1UYVflYH87qt69RzAuMKVTFUTMrrUWWIzpOW4GsdwWyinbyzaPHQ3ceVZPHw8nrB-WZ3WncJLXeDDepQrm2YLl_br_xJgU1KmcKfxIrgntnKd9bQRMVzR-OtGAFQx2L3AWyJlNsy31XrXtGccpZXSga_ZtCdZVfOGAyIttNHrXoS-glJvOODdoe2428CTRaygmXA5EyInmNONIzh71PvntUYfd4ZGcMGmCVSkHgvUOyBli_b_BHjF3up96NcG8-J6qOJStrHxcPsS5nS0yT6KmQylEbR8AJ6apdV6ucxaTSm99pw9GQ6JHY-CcQ","dp":"dKSCbqy2TXVk6JAr1K4J4qPh9X34NpPGA49EIt_3r-te85oGhkC0cqN3uIgHFDBqNf-B1dnQ6BOsIHmztZBfu8YHiwt8LhtxpyyHCbdRgIE4_iKn2YQ1NAnInY7gEzAH_kC0VkQzun-aWWW7NkBmcJVFL0jIMe822ARs56xZaxT9VvsDARhGMPNoub2XixsaB9UN6UymKv7QbfWlaeLzgizGCA8t_6jAW3AQT1gK8b4QRu7lldzjjDh09t6pHCXEMYoor7FIgf0Db7xfjfDFKJcvC2-RGI116dMaLmM-jtI4jmOlakfUc3XMVgXxbyx2n5x5sbiqGmmHhVC15u_ssw","dq":"G4bv3aJRP-kh6XB4HT954WSISM5hMXMEFNsQinL_YppitFQSpGNPI6YFAmSBdy38J8HHQxdYnCD1hVE0G9k45eP5ntUy0806z0_kEac--JC-ijycjoCsntVX_LdK5bn4XPu5nHVgULAhAkwEOz4fwa5NkXjkU2liy-2Yqzg0Kz_Vp5YFF9RDP32fWyNNX6eGmm6y4s_qpan_CkuTEz2Ei91SetlWC4Q6eJYcy9QJVDEj84a9UoafvTP7ZO0nxhBcjX0uQeXLBbg0IMTXuq0lqbMa6NXYsdXw-QAV0BP2ShIPTv_pRDC-eAG8_S26guRH9tLhYEoJTohka_FcDGLg0Q","qi":"CqQy8ljGycyTF6w_4VD72PebXrdogUpJKwpQmud7L6Hs-i6fXfkRs92wqveTL_UNg7e_8tzOU1drlfoznISkhdHsElLCe71t0HHRuAPcBr5mI5aNC52pP9E-hctwQzd-GOhko-2g7uNSLkckLg0jijx_K2nYtOt26QuO99aiWjXakMQ42fhYZjk-mewYux14kiSEQnss_a1yYEldDXnmh-bqy3JhjO0ZvNY2KUWQyhVxkemUPGXNONsXVcI3MJ5skh6q9DJ4Xh9kLf0fVkypbGp2kfni6eGfNFh-c69sVt8-srBJZeJ8l3JAygm4wN3x9p00OKa6nqa6OGTTTKOt5g"}