apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/universe-datascraper-block-producer
patchesStrategicMerge:
  - patch-affinity.yaml
patchesJson6902:
  - path: patch-replicas.yaml
    target:
      group: apps
      kind: Deployment
      name: universe-datascraper-block-producer
      version: v1
commonLabels:
  app: indexer
  component: universe-datascraper-block-producer
  environment: prod
configMapGenerator:
  - name: universe-datascraper-block-producer
    literals:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIARDONMETSDXC2YHRN
      - AWS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/076129510628/prod-datascraper-block-backwards.fifo
      - ETHEREUM_NETWORK=mainnet
      - APP_ENV=prod
      - ETHEREUM_QUORUM=2
      - DEFAULT_START_BLOCK=14413456 #Latest block as of March 18, 2022 7:54pm EST
      - DEFAULT_END_BLOCK=4966905 #First block from ERC-721 standard release date: 2018-01-24
      - BLOCK_DIRECTION=down