apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/universeapp-backend
  - secret.yaml
patchesStrategicMerge:
  - patch-ingress.yaml
  - patch-affinity.yaml
  - patch-redis.yaml
patchesJson6902:
  - path: patch-hostname.yaml
    target:
      group: networking.k8s.io
      kind: Ingress
      name: universeapp-backend
      version: v1beta1
  - path: patch-replicas.yaml
    target:
      group: apps
      kind: Deployment
      name: universeapp-backend
      version: v1
commonLabels:
  app: backend
  component: universeapp-backend
  environment: dev
configMapGenerator:
  - name: universeapp-backend
    literals:
      - APP_PORT=3000
      - AWS_BUCKET_NAME=universeapp-assets-dev
      - AWS_ACCESS_KEY_ID=AKIARDONMETSKMYFQ4CD
      - AWS_S3_BASE_URL=https://universeapp-assets-dev.s3.amazonaws.com
      - DB_DATABASE_NAME=kekdao
      - DB_HOST=dev-universe.cotqfbtbif7j.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DB_USERNAME=kekdao
      - ETHEREUM_NETWORK=rinkeby
      - INFURA_PROJECT_ID=3c1876c59e1342d89b97cd7a6500dca7
      - MORALIS_APPLICATION_ID=qWxPrLYp3Ug7ky6eyh7LIvVg2oF3q7GXNCU8z7nw
      - MORALIS_SERVER_URL=https://6ynjucpsxnva.usemoralis.com:2053/server
      - MORALIS_MASTER_KEY=JdTFna2xp50nxsrFCNolNci9rTtSZzDrneMlrVKN
      - REDIS_HOST=redis-master
      - REDIS_PORT=6379
      - GOOGLE_SENDER_EMAIL=noreply@universe.xyz
      - REPORT_VIOLATIONS_EMAIL=reports@universe.xyz
      - ETHEREUM_QUORUM=2
      - COLLECTION_EDIT_ADDRESS=0x5473580406D12E1cBD4c00B77e158FfF0CE9424e

