apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/atlasdb-proxy
patchesStrategicMerge:
  - patch-cmd-args.yaml
  - patch-service.yaml
commonLabels:
  app: backend
  component: atlasdb-proxy
  environment: dev