apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/universe-datascraper-metadata-producer
  - secret.yaml
patchesStrategicMerge:
  - patch-affinity.yaml
patchesJson6902:
  - path: patch-replicas.yaml
    target:
      group: apps
      kind: Deployment
      name: universe-datascraper-metadata-producer
      version: v1
commonLabels:
  app: indexer
  component: universe-datascraper-metadata-producer
  environment: alpha
configMapGenerator:
  - name: universe-datascraper-metadata-producer
    literals:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIARDONMETSALD6H4TH
      - AWS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/076129510628/datascraper-token.fifo
      - ETHEREUM_NETWORK=mainnet
      - INFURA_PROJECT_ID=978f8f87fbdd4ea0b94fe0ab245b06db
      - INFURA_PROJECT_SECRET=775db2b9d9b94b8189665f00bceae69b
      - SESSION_SECRET=XYZDAO
      - IPFS_GATEWAY=https://ipfs.infura.io/ipfs/
      - APP_ENV=alpha
      - PORT=8080