apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/api
  - secret.yaml
patchesStrategicMerge:
  - patch-ingress.yaml
  - patch-affinity.yaml
patchesJson6902:
  - path: patch-hostname.yaml
    target:
      group: networking.k8s.io
      kind: Ingress
      name: api
      version: v1beta1
  - path: patch-replicas.yaml
    target:
      group: apps
      kind: Deployment
      name: api
      version: v1
commonLabels:
  app: backend
  component: api
  environment: alpha 
configMapGenerator:
  - name: api
    literals:
      - KD_API_PORT=3001
      - KD_API_DEV_CORS=true
      - KD_API_DEV_CORS_HOST=*
      - KD_DB_HOST=alpha-universe.cotqfbtbif7j.us-east-1.rds.amazonaws.com
      - KD_DB_PORT=5432
      - KD_DB_SSLMODE=disable
      - KD_DB_DBNAME=kekdao
      - KD_DB_USER=kekdao
      - KD_STORABLE_KEK_ADDRESS=0x618679dF9EfCd19694BB1daa8D00718Eacfa2883
