apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-proxy
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: proxy
        image: gcr.io/google_containers/proxy-to-service:v1
        ports:
        - name: opensearch
          protocol: TCP
          containerPort: 443
      serviceAccount: default
