apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
patchesStrategicMerge:
  - patch-cmd-args.yaml
  - patch-service.yaml
commonLabels:
  app: backend
  component: opensearch-proxy
  environment: dev