apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/postgres-proxy
patchesStrategicMerge:
  - patch-cmd-args.yaml
  - patch-service.yaml
patchesJson6902:
  - path: patch-deployname.yaml
    target:
      group: apps
      kind: Deployment
      name: postgres-proxy
      version: v1
  - path: patch-svcname.yaml
    target:
      kind: Service
      name: postgres-proxy
      version: v1
commonLabels:
  app: backend
  component: postgres-proxy-nft
  environment: dev
