apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- namespace.yaml
- sources
- redis
- api
- scrape
- notifications
- postgres-proxy
- postgres-proxy-nft
- universeapp-backend
- marketplace-backend
- marketplace-indexer
- universe-watchdog
- documentdb-proxy
- atlasdb-proxy
- universe-datascraper-api
- universe-datascraper-mediafiles-consumer
- universe-datascraper-mediafiles-producer
- universe-datascraper-mediafiles-consumer-backwards
- universe-datascraper-mediafiles-producer-backwards
- universe-datascraper-metadata-consumer
- universe-datascraper-metadata-producer
- universe-datascraper-metadata-consumer-backwards
- universe-datascraper-metadata-producer-backwards
- universe-datascraper-transfer-consumer
- universe-datascraper-transfer-producer
- universe-datascraper-contract-reader
- universe-datascraper-owners-consumer
- universe-datascraper-owners-producer
- universe-datascraper-monitor-consumer
- universe-datascraper-monitor-consumer-backwards
- universe-datascraper-monitor-producer
- universe-datascraper-monitor-producer-backwards

images:
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/kekbackend
  newTag: 962fe4f
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/marketplace-backend
  newTag: dev-v1.0.7.1-fe75d37
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/marketplace-indexer
  newTag: main-095c239
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-api
  newTag: universe-v1.0.2-005a5fa
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-contract-reader
  newTag: universe-marketplace-v1.1.0-b8869d9
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-mediafiles-consumer
  newTag: universe-marketplace-v1.1.0-0dac943
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-mediafiles-consumer-backwards
  newTag: universe-marketplace-v1.1.0-0dac943
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-mediafiles-producer
  newTag: universe-marketplace-v1.1.0-b13684d
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-mediafiles-producer-backwards
  newTag: universe-marketplace-v1.1.0-b13684d
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-metadata-consumer
  newTag: universe-marketplace-v1.1.0-809884f
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-metadata-consumer-backwards
  newTag: universe-marketplace-v1.1.0-809884f
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-metadata-producer
  newTag: main-8acff25
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-metadata-producer-backwards
  newTag: main-8acff25
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-monitor-consumer
  newTag: universe-marketplace-v1.1.0-33785e8
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-monitor-consumer-backwards
  newTag: universe-marketplace-v1.1.0-33785e8
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-monitor-producer
  newTag: universe-marketplace-v1.1.0-0c9e286
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-monitor-producer-backwards
  newTag: universe-marketplace-v1.1.0-0c9e286
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-owners-consumer
  newTag: universe-marketplace-v1.1.0-2ec85c5
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-owners-producer
  newTag: main-a8e3e23
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-transfer-consumer
  newTag: universe-marketplace-v1.1.0-2e5b77a
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-transfer-producer
  newTag: universe-marketplace-v1.1.0-0a89e75
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-watchdog
  newTag: 38f8fd3
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universeapp-backend
  newTag: 4e8c3fc
