apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - namespace.yaml
  - sources
  - redis
  - api
  - scrape
  - notifications
  - postgres-proxy
  - postgres-proxy-nft
  - universeapp-backend
  - logstash
  - opensearch-proxy
  - marketplace
images:
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/kekbackend
    newTag: "b9ff94a"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universeapp-backend
    newTag: "auctions-be939a0"
