apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- namespace.yaml
- sources
- redis
- api
- scrape
- notifications
- postgres-proxy
- postgres-proxy-nft
- universeapp-backend
- marketplace-backend
- marketplace-indexer
- universe-watchdog
- documentdb-proxy
- atlasdb-proxy
- universe-datascraper-api
- universe-datascraper-mediafiles-consumer
- universe-datascraper-mediafiles-producer
- universe-datascraper-mediafiles-consumer-backwards
- universe-datascraper-mediafiles-producer-backwards
- universe-datascraper-metadata-consumer
- universe-datascraper-metadata-producer
- universe-datascraper-metadata-consumer-backwards
- universe-datascraper-metadata-producer-backwards
- universe-datascraper-transfer-consumer
- universe-datascraper-transfer-consumer-backwards
- universe-datascraper-transfer-producer
- universe-datascraper-transfer-producer-backwards
- universe-datascraper-contract-reader
- universe-datascraper-owners-consumer
- universe-datascraper-owners-producer
- universe-datascraper-monitor-consumer
- universe-datascraper-monitor-consumer-backwards
- universe-datascraper-monitor-producer
- universe-datascraper-monitor-producer-backwards

images:
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/kekbackend
  newTag: 962fe4f
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/marketplace-backend
  newTag: dev-universe-v1.0.10-326b972
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/marketplace-indexer
  newTag: main-095c239
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-api
  newTag: dev-universe-v1.0.9.4-f2e8b65
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-contract-reader
  newTag: universe-v1.0.8-bda673a
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-mediafiles-consumer
  newTag: universe-v1.0.8-0476e91
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-mediafiles-consumer-backwards
  newTag: universe-v1.0.8-0476e91
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-mediafiles-producer
  newTag: universe-v1.0.8-a3106e4
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-mediafiles-producer-backwards
  newTag: universe-v1.0.8-a3106e4
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-metadata-consumer
  newTag: universe-v1.0.9-2344f1f
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-metadata-consumer-backwards
  newTag: universe-v1.0.9-2344f1f
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-metadata-producer
  newTag: universe-v1.0.8-7cf4cec
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-metadata-producer-backwards
  newTag: universe-v1.0.8-7cf4cec
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-monitor-consumer
  newTag: universe-v1.0.8-e4944b3
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-monitor-consumer-backwards
  newTag: universe-v1.0.8-e4944b3
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-monitor-producer
  newTag: universe-v1.0.8-5040ded
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-monitor-producer-backwards
  newTag: universe-v1.0.8-5040ded
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-owners-consumer
  newTag: universe-v1.0.8-f2e619f
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-owners-producer
  newTag: universe-v1.0.8-38f76fd
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-transfer-consumer
  newTag: universe-v1.0.9-8cc9a9d
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-transfer-consumer-backwards
  newTag: universe-v1.0.9-8cc9a9d
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-transfer-producer
  newTag: universe-v1.0.8-9ccc4b1
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-transfer-producer-backwards
  newTag: universe-v1.0.8-9ccc4b1
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-watchdog
  newTag: dev-universe-v1.0.9-3a28eaa
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universeapp-backend
  newTag: universe-v1.0.8-5716c22
