apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - namespace.yaml
  - sources
  - redis
  - api
  - scrape
  - notifications
  - postgres-proxy
  - postgres-proxy-nft
  - universeapp-backend
  - logstash
  - opensearch-proxy
  - marketplace-backend
  - marketplace-indexer
  - universe-watchdog
  - documentdb-proxy
  - universe-datascraper-api
  - universe-datascraper-mediafiles-consumer
  - universe-datascraper-mediafiles-producer
  - universe-datascraper-metadata-consumer
  - universe-datascraper-metadata-producer
  - universe-datascraper-transfer-consumer
  - universe-datascraper-transfer-producer
  - universe-datascraper-block-consumer
  - universe-datascraper-block-producer
  - universe-datascraper-contract-reader
  - universe-datascraper-transfer-monitor-consumer
  - universe-datascraper-transfer-monitor-producer

images:
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/kekbackend
    newTag: "962fe4f"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universeapp-backend
    newTag: "dev-0d69db2"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/marketplace-backend
    newTag: "main-7b16635"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/marketplace-indexer
    newTag: "main-deb9b44"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-watchdog
    newTag: "e94c154"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-api
    newTag: "main-7e6f6b6"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-mediafiles-consumer
    newTag: "main-0a73324"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-mediafiles-producer
    newTag: "main-98a8a6e"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-metadata-consumer
    newTag: "main-8d16dac"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-metadata-producer
    newTag: "main-7543043"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-transfer-consumer
    newTag: "main-4c8b539"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-transfer-producer
    newTag: "main-8817edf"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-block-consumer
    newTag: "main-887972d"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-block-producer
    newTag: "main-49fc9e2"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-contract-reader
    newTag: "main-689f722"
