apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - namespace.yaml
  - sources
  - redis
  - api
  - scrape
  - notifications
  - postgres-proxy
  - postgres-proxy-nft
  - universeapp-backend
  - logstash
  - opensearch-proxy
  - marketplace-backend
  - marketplace-indexer
  - universe-watchdog
  - documentdb-proxy
  - universe-datascraper-api
  - universe-datascraper-mediafiles-consumer
  - universe-datascraper-mediafiles-producer
  - universe-datascraper-metadata-consumer
  - universe-datascraper-metadata-producer
  - universe-datascraper-transfer-consumer
  - universe-datascraper-transfer-producer

images:
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/kekbackend
    newTag: "962fe4f"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universeapp-backend
    newTag: "dev-0d69db2"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/marketplace-backend
    newTag: "main-f9ffa20"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/marketplace-indexer
    newTag: "main-f0e89ac"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-watchdog
    newTag: "e94c154"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-api
    newTag: "main-f318cff"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-mediafiles-consumer
    newTag: "main-e0ca152"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-mediafiles-producer
    newTag: "main-f5b3466"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-metadata-consumer
    newTag: "main-ba86cea"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-metadata-producer
    newTag: "main-9bdb680"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-transfer-consumer
    newTag: "main-a0c2094"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-transfer-producer
    newTag: "main-5cdd073"
