apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/documentdb-proxy
patchesStrategicMerge:
  - patch-cmd-args.yaml
  - patch-service.yaml
  - patch-ingress.yaml
patchesJson6902:
  - path: patch-hostname.yaml
    target:
      group: networking.k8s.io
      kind: Ingress
      name: documentdb-proxy
      version: v1beta1
commonLabels:
  app: backend
  component: documentdb-proxy
  environment: alpha