apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/marketplace-backend
  - secret.yaml
patchesStrategicMerge:
  - patch-ingress.yaml
  - patch-affinity.yaml
patchesJson6902:
  - path: patch-hostname.yaml
    target:
      group: networking.k8s.io
      kind: Ingress
      name: marketplace-backend
      version: v1beta1
  - path: patch-replicas.yaml
    target:
      group: apps
      kind: Deployment
      name: marketplace-backend
      version: v1
commonLabels:
  app: backend
  component: marketplace-backend
  environment: prod
configMapGenerator:
  - name: marketplace-backend
    literals:
      - APP_PORT=8080
      - APP_ENV=prod
      - DB_DATABASE_NAME=kekdao
      - DB_HOST=prod-universe.cotqfbtbif7j.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DB_USERNAME=kekdao
      - DB_SSL=false
      - DB_SYNC=false
      - DB_MIGRATIONS=true
      - ETHEREUM_NETWORK=mainnet
      - ETHEREUM_CHAIN_ID=1
      - MARKETPLACE_CONTRACT=0xB720279a6fc982721771427aA3B6B3a135f81dE3
      - WATCHDOG_URL=http://universe-watchdog:8080
      - ETHEREUM_QUORUM=2
