apiVersion: v1
data:
    ALCHEMY_TOKEN: ENC[AES256_GCM,data:SYPGuWqfJCOx8qAdGk0lWLhO6IOkIlAgWAcAEBvUPckSZ3pnC8FMXEcuNS8=,iv:bLF511YvCm99TDgluQq1NRZ+Xdub6Nkqyl8qp3aELmk=,tag:EIabtyGtiJJzxh83o0axWA==,type:str]
    CHAINSTACK_URL: ENC[AES256_GCM,data:d9soxtRgkrJb/quQBcobrexRALbzxivBN9ZVypkNw4gGtxEpUmx/Tdwj2bXCyUgFzskqLIdMc1UdrM8xKER93IhTVTAT3s9uVz1KAe+sD8mduBL6eSK3lA==,iv:TkPdsyMWxF2RNS1bcN+QsgMS93OpK588Rw0NJY0EU7c=,tag:B/EDO1O2r6w63YeaiUmLwQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:jKTRHzT4YWFQHQDeHYCHoZetbxj/eHWaywIc0TlCWBA=,iv:5P1Y5VVH59JA1IIuIeOAinkrXIJ+q+XvhWEFzcBEQFA=,tag:xQDPTvuwgPGDOr55Vuhtlw==,type:str]
    INFURA_PROJECT_SECRET: ENC[AES256_GCM,data:h+ka6ngOKcCW5DH9QmxTL5nvp4dpai+wD43IlKB2GviZiPjWQybOTDn72ks=,iv:4x79LU+wXdluqMsDi8OSnx4tcux3a3N6Zk5wtHNqTzc=,tag:ieo/im8gb2mAHOdUtZBbvQ==,type:str]
    INFURA_PROJECT_ID: ENC[AES256_GCM,data:3z+HtfWjBlNmC+2onlXLGp6S5dzmDQ/iguOvczX0t/iZk+SI9X6kxgLAFfM=,iv:FwtXZFKkR0qXOl06H+UlE/xY6rLNIVXIvTrBC/V7F1M=,tag:H3kUY11zInw7LjFbCAi1ew==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:0ZVg0tLdys0DlTOr2goPA3uhRW/tvD6pWdLXQA==,iv:Jna18myca/1hJ5GIeLolYiUW8wRsFhtuZftzJbDtlmA=,tag:Qhf7bFZSwf6/7gpAGud6hQ==,type:str]
    QUICKNODE_URL: ENC[AES256_GCM,data:l6fASBW1RHEsJAkTO0ybTujJMGSNMy2w7hznLTrZ1rRUvPMR1l+kYLVe+qKYihE2PWKFiFxgZawH9KbDpgo9zfWv55FUltBve4BHwgdqL134cCY61xIGEWShFS4xkV5CNaAXvyWUZWOmcq57,iv:kyFKIj6K49A4rrFCjN1/+Y12XDXv3QYI2qpVh8HMab0=,tag:1gBHkUaK+5qNbdruco5kGA==,type:str]
kind: Secret
metadata:
    name: marketplace-backend
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:076129510628:key/eab03aa9-c5da-4c1b-807b-686aed83fb2c
          created_at: "2022-03-24T13:31:04Z"
          enc: AQICAHj0qDpfgO9wb8Ne63a0VPqmK07P9Pqm4dt4axNmrKd7LAFe+nLh6SyUu7zpA/ZxLl3KAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbdudno72bieuxF/yAgEQgDtXcY0jwSG9ga1v52orDsiEdmkP9/MXzSKcllHhP1VaAR4fjw0scpsCkjnQvgmM9xg6Gw+T4xQDPojvzw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-24T13:31:04Z"
    mac: ENC[AES256_GCM,data:ipgo/ZAf+4mncf5vy5Yq/WSWEFypAVuy5oRd5eEFFhR25eUUJiImNkl8PK7hpPE/lfy/v5lmo3sQROCPeeFUgrbne3/UYWI7BXE1hv5NQ8qiqcPN3g1Oq76XyKDDmSpMXK0YjTHWQFnuZSvhoyCC1U+01jGhgDsULQxBasBvOoQ=,iv:zAPp9h/spWfLKiQB1d9IoMBqecLLl+GNJaK19ST5Jcc=,tag:CZWXcI9eh21+9QQLqDDqtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
