apiVersion: v1
data:
    DB_PASSWORD: ENC[AES256_GCM,data:HiZYI4L7ly64eRYSoWfljfxoo+j8X+/SKg6xJWfM1xQ=,iv:h8y//ENKH211Bi7Rburo5DS+owmpyOiJSt0e+OWCPGs=,tag:yWLSJov3azMsdbU7/iS+Fw==,type:str]
    INFURA_PROJECT_SECRET: ENC[AES256_GCM,data:hchcqv2hDBxnQwA37r2ie/dfoq3tpAhqTnSWgECG4gEjYdAKCaX6JxiH70E=,iv:DZrOIGThIoo/q5nZgyty13StiM2uDHckbdSzDoz0UIw=,tag:8/S8RCKz3PITEgeKy6yzGg==,type:str]
    INFURA_PROJECT_ID: ENC[AES256_GCM,data:SVOIQB+OFf1lKnVJfVpoQsF/RvgD1GNXvdoVhSYLCwZHykbJjrmOSsvTAS4=,iv:Y21QaXTvuZp9TZnSETVUKpyCZPveqJ1X/OrzZy/4SL0=,tag:XLhObFO/4gsDZPFUajj0ZA==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:ypqGvFq6hWfV44ZqgprK+GebOaDNg9QcysGSfQ==,iv:RjPf107O8Z8IAHcSZZZw5GzeGGHJCeZDo/b89xUAl+A=,tag:3RLRIXCy6toh/ypLlyxERg==,type:str]
kind: Secret
metadata:
    name: marketplace-backend
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:076129510628:key/eab03aa9-c5da-4c1b-807b-686aed83fb2c
          created_at: "2022-03-18T21:35:57Z"
          enc: AQICAHj0qDpfgO9wb8Ne63a0VPqmK07P9Pqm4dt4axNmrKd7LAGXGKBtsheoVHacSmKWSF9NAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMatVjnZZyJKd9Xwq9AgEQgDsDCQO29abXgDTa8Nsb4mH3XkxdlTZ5UxBDHZEg8IN8HXD7Nc66PCbZPXD1564QrCM2gRT8R7i0B6IifQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-18T21:35:57Z"
    mac: ENC[AES256_GCM,data:o2evzkuXKdXZxp9mv7+diAywM46jT8m6039m9HNQw1+POn5y7cOL7FuHV4c4/3NKkzs4xKdWovsRsmcT78tFRtmQOwMr6nRevyzECfwoQVfuLhwCPcxmME3ihZongjOVSMWpqc7fRYtH4erfpLTHOt5oX8noYhs2ADgH4LHYCZU=,iv:XMPPsoACHThQGSG0C0gkSGvl+WCOYpiAXBZor1svWlE=,tag:1tl1H6jTTSqkCh7zJ3aOSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
