apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/universe-datascraper-contract-reader
patchesStrategicMerge:
  - patch-affinity.yaml
patchesJson6902:
  - path: patch-replicas.yaml
    target:
      group: apps
      kind: Deployment
      name: universe-datascraper-contract-reader
      version: v1
commonLabels:
  app: indexer
  component: universe-datascraper-contract-reader
  environment: dev
configMapGenerator:
  - name: universe-datascraper-contract-reader
    literals:
      - ETHEREUM_NETWORK=rinkeby
      - APP_ENV=dev
      - PORT=8080
      - ETHERSCAN_API_KEY=XW34D32UMKX17RAESAADSRSAVY58U9EMD7
      - RECENT_BLOCK_GAP=100
      - ETHEREUM_QUORUM=2