apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/scrape
  - secret.yaml
patchesStrategicMerge:
  - patch-affinity.yaml
  - patch-env.yaml
patchesJson6902:
  - path: patch-replicas.yaml
    target:
      group: apps
      kind: Deployment
      name: scrape
      version: v1
commonLabels:
  app: backend
  component: scrape
  environment: auctions
configMapGenerator:
  - name: scrape
    literals:
      - KD_API_PORT=3001
      - KD_API_AUCTIONS_CORS=true
      - KD_API_AUCTIONS_CORS_HOST="*"
      - KD_DASHBOARD_PORT=3000
      - KD_DASHBOARD_CONFIG_MANAGEMENT_ENABLED=true
      - KD_DB_HOST=auctions-universe.cotqfbtbif7j.us-east-1.rds.amazonaws.com
      - KD_DB_PORT=5432
      - KD_DB_SSLMODE=disable
      - KD_DB_DBNAME=kekdao
      - KD_DB_USER=kekdao
      - KD_ETH_CLIENT_POLL_INTERVAL=15s
      - KD_FEATURE_BACKFILL_ENABLED=false
      - KD_FEATURE_LAG_ENABLED=true
      - KD_FEATURE_LAG_VALUE=2
      - KD_FEATURE_AUTOMIGRATE_ENABLED=true
      - KD_LOGGING="*=info"
      - KD_REDIS_SERVER=redis-master:6379
      - KD_REDIS_LIST=kekdao
      - KD_ABI_PATH=./abis
      - KD_STORABLE_KEK_ADDRESS=0x41E88dc0dfA5455E64327484F1862332413520da
      - KD_STORABLE_SUPERNOVA_ADDRESS=0xb71fF62AEDFDCc68B72bEd3218c3cA137Dab0403
      - KD_STORABLE_GOVERNANCE_ADDRESS=0x63172A077b3740Dd9Ae311F81c72Edb7170F135c
      - KD_STORABLE_YIELDFARMING_ADDRESS=0xe3Ad77D3726357591cE665b051a41252aD2CDF4E
      - KD_STORABLE_AUCTION_ADDRESS=0x1753aca48fa1933e7cf3525652953873c63363ba
      - KD_STORABLE_UNIVERSE_ADDRESS=0xbdfff8b0306fd7af337c4842350625f50fd2be3a
      - KD_STORABLE_UNIVERSE_PUBLIC_COLLECTION=0x5a322b56ed080c559da183b69aa720d19690eaf2
