apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alpha
resources:
- namespace.yaml
- sources
- redis
- api
- notifications
- postgres-proxy
- scrape
- universeapp-backend
- documentdb-proxy
- marketplace-backend
- marketplace-indexer
- universe-watchdog
- universe-datascraper-api
- universe-datascraper-mediafiles-consumer
- universe-datascraper-mediafiles-producer
- universe-datascraper-metadata-consumer
- universe-datascraper-metadata-producer
- universe-datascraper-transfer-consumer
- universe-datascraper-transfer-producer
- universe-datascraper-block-consumer
- universe-datascraper-block-producer
- universe-datascraper-contract-reader
- universe-datascraper-transfer-monitor-consumer
- universe-datascraper-transfer-monitor-producer
- universe-datascraper-owners-consumer
- universe-datascraper-owners-producer
- universe-datascraper-monitor-consumer
- universe-datascraper-monitor-producer

images:
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/kekbackend
  newTag: 962fe4f
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/marketplace-backend
  newTag: alpha-universe-v1.0.5-2-19f1ed8
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/marketplace-indexer
  newTag: main-095c239
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-api
  newTag: main-95d877f
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-block-consumer
  newTag: main-27893a1
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-block-producer
  newTag: main-d126422
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-contract-reader
  newTag: main-5d776c8
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-mediafiles-consumer
  newTag: main-697187e
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-mediafiles-producer
  newTag: main-d31c23e
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-metadata-consumer
  newTag: main-3b32b34
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-metadata-producer
  newTag: main-e1e65ba
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-monitor-consumer
  newTag: main-5268ed4
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-monitor-producer
  newTag: main-75d0eb1
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-owners-consumer
  newTag: main-515839b
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-owners-producer
  newTag: main-a8e3e23
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-transfer-consumer
  newTag: main-e116be2
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-transfer-producer
  newTag: main-1b857f4
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-watchdog
  newTag: 38f8fd3
- name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universeapp-backend
  newTag: 4e8c3fc
