apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alpha
resources:
  - namespace.yaml
  - sources
  - redis
  - api
  - notifications
  - postgres-proxy
  - scrape
  - universeapp-backend
  - documentdb-proxy
  - marketplace-backend
  - marketplace-indexer
  - universe-watchdog
  - universe-datascraper-api
  - universe-datascraper-mediafiles-consumer
  - universe-datascraper-mediafiles-producer
  - universe-datascraper-metadata-consumer
  - universe-datascraper-metadata-producer
  - universe-datascraper-transfer-consumer
  - universe-datascraper-transfer-producer
  - universe-datascraper-block-consumer
  - universe-datascraper-block-producer
  - universe-datascraper-contract-reader
  - universe-datascraper-transfer-monitor-consumer
  - universe-datascraper-transfer-monitor-producer
  - universe-datascraper-owners-consumer
  - universe-datascraper-owners-producer
  - universe-datascraper-monitor-consumer
  - universe-datascraper-monitor-producer

images:
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/kekbackend
    newTag: "962fe4f"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universeapp-backend
    newTag: "3bf4d97"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/marketplace-backend
    newTag: "main-7b16635"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/marketplace-indexer
    newTag: "main-deb9b44"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-watchdog
    newTag: "e94c154"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-api
    newTag: "main-7e7acff"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-mediafiles-consumer
    newTag: "main-7cc3176"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-mediafiles-producer
    newTag: "main-4640a09"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-metadata-consumer
    newTag: "main-ba86cea"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-metadata-producer
    newTag: "main-d4873be"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-transfer-consumer
    newTag: "main-6574e0f"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-transfer-producer
    newTag: "main-8a76145"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-block-consumer
    newTag: "main-93c1a45"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-block-producer
    newTag: "main-1b32d47"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-contract-reader
    newTag: "main-59a7936"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-owners-consumer
    newTag: "main-a6da80c"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-owners-producer
    newTag: "main-d30746a"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-monitor-consumer
    newTag: "main-236363e"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-monitor-producer
    newTag: "main-4bff432"
