apiversion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alpha
resources:
  - namespace.yaml
  - sources
  - redis
  - api
  - notifications
  - postgres-proxy
  - scrape
  - universeapp-backend
  - documentdb-proxy
  - universe-datascraper-api
  - universe-datascraper-mediafiles-consumer
  - universe-datascraper-mediafiles-producer
  - universe-datascraper-metadata-consumer
  - universe-datascraper-metadata-producer
  - universe-datascraper-transfer-consumer
  - universe-datascraper-transfer-producer
  - universe-datascraper-block-consumer
  - universe-datascraper-block-producer
  - universe-datascraper-contract-reader

images:
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/kekbackend
    newTag: "962fe4f"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universeapp-backend
    newTag: "3bf4d97"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-api
    newTag: "main-f318cff"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-mediafiles-consumer
    newTag: "main-9450ade"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-mediafiles-producer
    newTag: "main-98a8a6e"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-metadata-consumer
    newTag: "main-ba86cea"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-metadata-producer
    newTag: "main-7543043"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-transfer-consumer
    newTag: "main-8d562fc"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-transfer-producer
    newTag: "main-8e65ace"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-block-consumer
    newTag: "main-1174932"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-block-producer
    newTag: "main-af57667"
  - name: 076129510628.dkr.ecr.us-east-1.amazonaws.com/universe-datascraper-contract-reader
    newTag: "main-eced514"
