apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: alpha
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: eks-app
  path: ./universe-apps/environments/auctions
  prune: true
  validation: client
  decryption:
    provider: sops
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: api
      namespace: alpha
    - apiVersion: apps/v1
      kind: Deployment
      name: scrape
      namespace: alpha
    - apiVersion: apps/v1
      kind: Deployment
      name: notifications
      namespace: alpha
