apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dev
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: eks-app
  path: ./universe-apps/environments/dev
  prune: true
  validation: client
  decryption:
    provider: sops
  # healthChecks:
  #   - apiVersion: apps/v1
  #     kind: Deployment
  #     name: api
  #     namespace: dev
  #   - apiVersion: apps/v1
  #     kind: Deployment
  #     name: scrape
  #     namespace: dev
  #   - apiVersion: apps/v1
  #     kind: Deployment
  #     name: notifications
  #     namespace: dev
