apiVersion: v1
data:
    ALCHEMY_TOKEN: ENC[AES256_GCM,data:ow51dCv0RCGGqiM0a8Uy7NKZCFC0InrkfnL2tP3QSX+9jZAQCmrv9bn0adY=,iv:4Q/0b+PFrE+UvuwutTu3E4MipiIvukP7SXL90Bmok+c=,tag:i/ZgEO+w7ghvxd5TAQWt9Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:kVIO8OIAYMP7xyk7nsQAZH5H4V8kq/XLi1Wfgf6vFJ8MB8flacDEDmj45A+LBAObDmnfxoz4QKU=,iv:ErIg8wAgPCJwt1PVkIgzDOZS3pQfDklmSN662aPOpIM=,tag:FfnZKPuKg5zyufhpSBgdWg==,type:str]
    INFURA_IPFS_PROJECT_SECRET: ENC[AES256_GCM,data:X9Fph2Tdt8wEZDDY5SvCC+0Bsv40a0D59z7lBMvn3njoqNZYZyHtsknpkHk=,iv:pSO0z7yrntACp1nreN+bnB9g1lIxN4Ed8p+E7Z158U4=,tag:JdBcPpQ4clM40ZIwrTy8+Q==,type:str]
    INFURA_PROJECT_SECRET: ENC[AES256_GCM,data:iOIq85eTj1V2a+wXP+7Oi8Q33sM7rUdO44MARaTpX80GB48/kvxTJj8rf9I=,iv:arKwkpX5pe6Ke0onlcjYVoS2LnwUduySNU9VJiePX8Y=,tag:zDgNAV0t+QrybruTAt/wrA==,type:str]
    MONGODB_URI: ENC[AES256_GCM,data:iarn0PipOOV77QdGgw5J0rh0UPQ8LZw+pAWn6ili6VJT3Kpj+Mq1DHMblYi38tCbvU4NAs72IwNT1Lls/T1gADfr9Iygkw4X0ur7XqMi9bJWmQKALq3ebGdj9wB4kz12B9qGIaZZwEqU1XFN5goj+9rHDlikKuB1FjsGJ9v/qjA/gBjnA+XSFMmDLRj48Ik4b34pRjYCdzOjARAL8DjxL/6B5aeEwDptcfb8hccpqJSMqoKOUVW09zWBgBmA0MoCZ1qqOVjT+7vMxEybMiH25WOqmKzm2YlDkjWpELhk5J8rTQsrM8YYkAbvik/coGtrjFpBG51XoJoywkDX4OKCo2Jmvpv5nwowLuLYbRb2bRz9OT/hcUexmUKH3EYJysLbUnUpn2JffUiSoVhMAVTVp3YqfEiX6m0CRgZGsqjmBe90W8YpocalJWyIyUl4yAS47QhbJ+2ThYo=,iv:usLw3Q4UYOJ5woD5skZ0I5SQ0UyJHnBmlTqam1zMzB8=,tag:nt54hmwX0l0WB8MQW+IWag==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: universe-datascraper
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:076129510628:key/f019707e-98d5-454b-adcd-a4b8ccc35f44
          created_at: "2022-03-04T18:20:25Z"
          enc: AQICAHicCjtoxmBmz2MO3QTlS3370ieytvfowEbSDe18IeRxZAHK2na93DSQRkK7LjAS/40kAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMfy/GrokflLI9fgmxAgEQgDvgtMpq6GwkUZywOU3lYX/Ai8ZPusDM1uUQmlNmqdlhQYSqsovOWTX7hc8SIZpml+Ci2n4tV9ITPCL4LQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-04T18:20:25Z"
    mac: ENC[AES256_GCM,data:wnuetQtctlS/fQTcIwWzRP0ft16iwhaxg9AFcMqU0mYDg8vgeCteotkTksTVNoP4x9vSVjISaoBrDRtDVd5HlIBwIPOXTUqahHHdNM1XeX7aGWcrAt90aPvgZcntxORBWP9d5QICkjOQzRFtZuv0BMGLILW2SPbNRf64HvTKI8E=,iv:dx6WSzh0se6AwPxF8TqeirK8TAQLOfs1XpAHA0OTvyk=,tag:N3FWCkiH39DX8BmwI/PjcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
