apiVersion: v1
data:
    ALCHEMY_TOKEN: ENC[AES256_GCM,data:BguabmCEfXK4BE05AjN34QMFHziNtqvrvgT0ueMgyYsmTIysTRELwU4vITU=,iv:gTZQqDJzSEFFTrqspD/zWSdT59+rHyx9h91zahZD6UM=,tag:1AVsTS4Oj/RnAn3c7FW43Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ozG2UVHb7JZWoTjPwaHF6egI4yYdUrs/OpDgO+gPy64wwIYNJk9+1w6gDW15kBZEHXTz685qLGk=,iv:jAYjL6i2xqA6PAegca1Frnlx/nXpvzZSc4kbg2hR/aE=,tag:vTuPWVkoa9HKjfb4zABV1A==,type:str]
    INFURA_IPFS_PROJECT_SECRET: ENC[AES256_GCM,data:p1CWtb9e0v1WgU8Tgz9tVqslln2YYTBddL3lNQKLQdc5hDmyquGyLw9n4KQ=,iv:Vvc3KNwYJgxG9bfT2SNmQgyPsFOxS9Sm8PeQTitAgTc=,tag:QLDqD6cHBxfQGeika4O9kA==,type:str]
    INFURA_PROJECT_SECRET: ENC[AES256_GCM,data:yBPH99bo8ERfjsk8GT0gWKg76o7fNeiAWVXX5YBkHOp54W4796vLQqNcV1M=,iv:LFq84+adWCoiqcOYg/KvZKlGchmAbvlsJOtbLv0Ries=,tag:+mCwkEnzITaNrCKiNQcqwQ==,type:str]
    MONGODB_URI: ENC[AES256_GCM,data:sjS6bW3Ue2NkfzQlpnTmB2n8cx8frzLTxR83gdw3gWdoMYdaHDf3uWNm6xxb5T3j4phAm0JbhtMoJF0xJn9cwf19ebPVG7WR1togcn7y7NRsRuS+8NJIeYLkv4UCOIqETdTKoAX3BGRx8CgGAaB2kU1V5xI5j2QRqBCRUKS0yiSoBIIn3affLjsx8iB7ZxO4lPIp58iWSqsRExTLkyH0DAJbjMllhXIw1Ii8n20UtZDmk5mp0dxwk/OTxGj95gNuQ3+jkeT6GH5Q4d9teWBaU8T2dAJCAI8CauTDVs+trniSPxclMe6OuPXGxBFq+go1yGvCcrRhM81a3PTMDH24xxMnHpaoIrlahjEb9OiIJzKeW90rpKGAZzFOlu4AcUfmMgt2srdCOOKCQOJLvip+NJgPrTVrkL+GwWDSdJnx9iKrtyfR0+HbdBY0bxVySoK/1TWESA==,iv:Z5FmkYGS0vjH7D8tsTON1keCZ2FrhgwlvsDiVyaWfdQ=,tag:cMCLty/+YajnIHHILf7K6Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: universe-datascraper
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:076129510628:key/f019707e-98d5-454b-adcd-a4b8ccc35f44
          created_at: "2022-03-04T20:01:56Z"
          enc: AQICAHicCjtoxmBmz2MO3QTlS3370ieytvfowEbSDe18IeRxZAGXRD/wXWtMNFb/jAyyRNerAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVw8OkS9/SAUipcwGAgEQgDuWbu/Zg3k55leYhKfRy5aP0X846lk7EjbZK0jNCv3qH52oXOCOrvKEpJATOkpyRyAGyS730MYI3nqIWg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-04T20:01:57Z"
    mac: ENC[AES256_GCM,data:GEgSKJ5xRKCuCi1NC8buyUVh2iOdeIEsz7q5D+l71cGibI76zIBsF6wkVC7XrdBwUBeql2rg3GbC0hAlaZsSWjLUFo7+OnhpRQAORjAv1d1/NIree45dzKBRoNeQjkbZj2nIcsPW0beIHC2aLpE6LcotJRjG/KbQAm7vXLElm6I=,iv:ORSZi5O81PXW8jCNSaWWWhiRO0Q1CEby/knfYuKEb/k=,tag:Wzy+qNcxtIhXKP9LmfmGXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
