apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/universe-datascraper-transfer-consumer
patchesStrategicMerge:
  - patch-affinity.yaml
patchesJson6902:
  - path: patch-replicas.yaml
    target:
      group: apps
      kind: Deployment
      name: universe-datascraper-transfer-consumer
      version: v1
commonLabels:
  app: indexer
  component: universe-datascraper-transfer-consumer
  environment: alpha
configMapGenerator:
  - name: universe-datascraper-transfer-consumer
    literals:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIARDONMETSALD6H4TH
      - AWS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/076129510628/datascraper-transfer.fifo
      - ETHEREUM_NETWORK=mainnet
      - APP_ENV=alpha
      - PORT=8080
      - ETHEREUM_QUORUM=2
      - MONGODB_URI=mongodb+srv://universe-db-account:y7rYKn6Bw41PbB3E@universe-dev-cluster-at.lrbek.mongodb.net/dev-universe-datascraper?retryWrites=true&w=majority&ssl=true
      - BATCH_SIZE=500
      - BLOCKS_INTERVAL=500